[package]
name = "axxd"
version = "0.1.0"
authors = ["multicatch <cezaryre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"

num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
