[package]
name = "axxd"
description = "A simple axx file decryption tool."
version = "0.2.0"
authors = ["multicatch <cezaryre@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/multicatch/axxd"
repository = "https://github.com/T1erno/axxd"
readme = "README.md"

[dependencies]
clap = "2.33.3"
rpassword = "5.0.1"
flate2 = "1.0"
encoding_rs = "0.8"
num-traits = "0.2"
num-derive = "0.4"

aes = "0.8"
cbc = "0.1"
sha1 = "0.10"
sha2 = "0.10"
hmac = "0.12"
pbkdf2 = "0.12"
cipher = { version = "0.4", features = ["block-padding"] }
